#Configuracion del Juego
#Sun Jun 07 18:03:08 GMT-03:00 2026
efectosSonido=true
musicaFondo=true
pantallaCompleta=false
pistaMusical=original
skinPersonaje=original
teclaCavar=SPACE
teclaEfectos=Q
teclaIniciar=ENTER
teclaMusica=W
