#Configuracion del Juego
#Fri Jun 05 21:06:26 ART 2026
efectosSonido=true
musicaFondo=true
pantallaCompleta=false
pistaMusical=original
puntuacionMaxima=11
skinBarras=original
skinCancha=original
skinPelota=triangulo
teclaAbajo1=DOWN
teclaAbajo2=S
teclaArriba1=UP
teclaArriba2=W
