#Configuracion del Juego
#Tue Aug 04 15:56:01 GMT-03:00 2026
efectosSonido=true
musicaFondo=true
pantallaCompleta=false
pistaMusical=alternativa
skinInvasores=alternativa
skinNave=alternativa
skinProyectiles=alternativa
teclaDerecha=39
teclaDisparo=32
teclaIzquierda=37
velocidad=RAPIDA
