#Configuracion de Pong
#Thu Jun 04 19:14:40 ART 2026
pantallaCompleta=true
pistaMusical=original
puntuacionMaxima=11
skinBarras=original
skinCancha=moderno
skinPelota=original
sonidoActivado=true
teclaAbajo1=DOWN
teclaAbajo2=S
teclaArriba1=UP
teclaArriba2=W
