#Configuracion del Juego
#Fri Jun 05 20:32:05 ART 2026
efectosSonido=true
musicaFondo=true
pantallaCompleta=true
pistaMusical=original
skinPersonaje=original
teclaCavar=SPACE
teclaEfectos=Q
teclaIniciar=ENTER
teclaMusica=W
