#Configuracion de Lode Runner
<<<<<<< HEAD
#Fri Jun 05 21:02:59 GMT-03:00 2026
=======

#Fri Jun 05 14:38:48 GMT-03:00 2026

>>>>>>> d5c57cf22c2b735fe32e9c62ab96b203e3e544e8
efectosDeSonido=true
musicaActivada=false
pantallaCompleta=true
pistaMusical=original
skinPersonaje=original
teclaCavar=SPACE
teclaEfectos=q
teclaIniciar=ENTER
teclaMusica=w
