#Configuracion del Juego
#Fri Jul 31 21:04:46 GMT-03:00 2026
efectosSonido=true
musicaFondo=true
pantallaCompleta=true
pistaMusical=original
skinPersonaje=original
teclaCavar=SPACE
teclaEfectos=Q
teclaIniciar=ENTER
teclaMusica=W
