#Configuracion de Lode Runner
#Sat May 30 15:20:56 GMT-03:00 2026
efectosDeSonido=true
musicaActivada=true
pantallaCompleta=false
pistaMusical=original
skinPersonaje=moderno
teclaCavar=SPACE
teclaEfectos=q
teclaIniciar=ENTER
teclaMusica=w
