#Configuracion del Juego
#Fri Jun 05 20:02:04 ART 2026

pantallaCompleta=false
pistaMusical=remix
skinInvasores=original
skinNave=original
skinProyectiles=original
sonido=true
teclaDerecha=39
teclaDisparo=32
teclaIzquierda=37
velocidad=MEDIA
