#Configuracion de Lode Runner
#Wed Jun 03 18:16:41 GMT-03:00 2026
efectosDeSonido=true
musicaActivada=true
pantallaCompleta=true
pistaMusical=retro
skinPersonaje=retro
teclaCavar=SPACE
teclaEfectos=q
teclaIniciar=ENTER
teclaMusica=w
