#Configuracion del Juego
#Fri Jun 05 22:50:13 ART 2026
efectosSonido=true
musicaFondo=true
pantallaCompleta=false
pistaMusical=8-bit
puntuacionMaxima=11
skinBarras=original
skinCancha=moderno
skinPelota=original
teclaAbajo1=DOWN
teclaAbajo2=S
teclaArriba1=UP
teclaArriba2=W
