#Configuracion del Juego
#Tue Jun 09 19:36:02 GMT-03:00 2026
efectosSonido=true
musicaFondo=true
pantallaCompleta=false
pistaMusical=original
skinInvasores=original
skinNave=original
skinProyectiles=original
teclaDerecha=39
teclaDisparo=32
teclaIzquierda=37
velocidad=MEDIA
