#Configuracion del Juego
#Tue Aug 04 12:12:35 GMT-03:00 2026
efectosSonido=true
musicaFondo=true
pantallaCompleta=true
pistaMusical=original
skinPersonaje=alternativo
teclaCavar=SPACE
teclaEfectos=Q
teclaIniciar=ENTER
teclaMusica=W
