#Configuracion del Juego
#Mon Aug 03 22:53:46 ART 2026
efectosSonido=true
musicaFondo=true
pantallaCompleta=true
pistaMusical=original
skinInvasores=original
skinNave=original
skinProyectiles=original
teclaDerecha=39
teclaDisparo=32
teclaIzquierda=37
velocidad=MEDIA
