#Configuracion del Juego
#Mon Aug 03 23:00:37 ART 2026
efectosSonido=true
musicaFondo=true
pantallaCompleta=true
pistaMusical=lofi
puntuacionMaxima=11
skinBarras=original
skinCancha=original
skinPelota=original
